
logging.level.root=WARN
logging.level.org.springframework.test=INFO
logging.level.com.chain4travel=DEBUG

grpc.server.port=50052
grpc.client.cmb-client.address=localhost:50052
grpc.client.cmb-client.negotiation-type=plaintext

cmbplugin.cache.enabled=true
cmbplugin.cache.search.ttl=1200
cmbplugin.cache.validation.ttl=1200
cmbplugin.cache.storageDir=cacheData

# Hardhat local network
cmbplugin.web3.network.chainUrl=http://127.0.0.1:8545
cmbplugin.web3.network.chainId=31337

cmbplugin.web3.smartContract.contractAddress=0x5FbDB2315678afecb367f032d93F642f64180aa3


# Columbus network (Camino testnet)
#cmbplugin.web3.network.chainUrl=http://columbus.c4t.itsquare.de:9650/ext/bc/C/rpc
#cmbplugin.web3.network.chainId=501
#
#cmbplugin.web3.smartContract.contractAddress=0x...


# Camino network (Camino mainnet)
#cmbplugin.web3.network.chainUrl=http://camino.c4t.itsquare.de:9650/ext/bc/C/rpc
#cmbplugin.web3.network.chainId=500
#
#cmbplugin.web3.smartContract.contractAddress=0x...
